export const MARKDOWN_VIEWER_CSS = `
.markdown-viewer-host{height:100%;min-height:0;color:#172033;background:#f6f7f9;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;--md-border:#d9dee7;--md-muted:#667085;--md-blue:#2563eb;--md-code:#f2f4f7}
.markdown-shell{height:100%;min-height:0;box-sizing:border-box;padding:16px;display:flex;flex-direction:column;gap:12px}
.markdown-header,.markdown-toolbar,.markdown-toolbar-group,.markdown-panel-header{display:flex;align-items:center;gap:8px}
.markdown-header{justify-content:space-between;align-items:flex-start}.markdown-title{font-size:16px;font-weight:650;word-break:break-word}.markdown-summary,.markdown-panel-header span:last-child{margin-top:3px;color:var(--md-muted);font-size:12px}
.markdown-status{padding:6px 10px;border:1px solid var(--md-border);border-radius:999px;background:#eef2f7;font-size:12px;font-weight:650;white-space:nowrap}.markdown-status.is-valid{color:#16794b;background:#ecfdf3;border-color:#abefc6}.markdown-status.is-invalid{color:#b42318;background:#fef3f2;border-color:#fecdca}
.markdown-toolbar{flex-wrap:wrap;justify-content:space-between}.markdown-toolbar-group{padding:6px;border:1px solid var(--md-border);border-radius:7px;background:#eef2f7}.markdown-toolbar button{min-height:30px;padding:5px 10px;border:1px solid #c5ccd8;border-radius:4px;background:#fff;color:#172033;font:inherit;font-size:12px;cursor:pointer}.markdown-toolbar button:hover{background:#f8fafc}.markdown-toolbar button.is-active,.markdown-toolbar button.is-primary{color:#fff;background:var(--md-blue);border-color:var(--md-blue)}.markdown-toolbar button.is-dirty{box-shadow:0 0 0 2px #fdb022}
.markdown-workspace{display:grid;grid-template-columns:minmax(0,1fr);grid-template-rows:minmax(0,1fr);gap:12px;flex:1;min-height:0}.markdown-workspace.is-split{grid-template-columns:minmax(320px,.9fr) minmax(360px,1.1fr)}.markdown-workspace.is-split .markdown-source-panel{grid-column:1;grid-row:1}.markdown-workspace.is-split .markdown-preview-panel{grid-column:2;grid-row:1}
.markdown-workspace.is-source .markdown-preview-panel,.markdown-workspace.is-source .markdown-source-panel{grid-column:1;grid-row:1}.markdown-workspace.is-source .markdown-preview-panel{visibility:hidden;pointer-events:none}.markdown-workspace.is-source .markdown-source-panel{z-index:1}
.markdown-panel{display:flex;flex-direction:column;min-height:0;border:1px solid var(--md-border);border-radius:7px;background:#fff;overflow:hidden}.markdown-panel-header{justify-content:space-between;padding:10px 13px;border-bottom:1px solid var(--md-border);background:#f8fafc;font-size:12px;font-weight:650}.markdown-panel-header span:last-child{margin:0;font-weight:400}
.markdown-preview{flex:1;min-height:0;overflow:auto;box-sizing:border-box;padding:24px;line-height:1.65;color:#172033}.markdown-preview>:first-child{margin-top:0}.markdown-preview>:last-child{margin-bottom:0}.markdown-preview h1,.markdown-preview h2,.markdown-preview h3,.markdown-preview h4{line-height:1.25;margin:1.35em 0 .65em}.markdown-preview h1{font-size:28px;padding-bottom:8px;border-bottom:1px solid var(--md-border)}.markdown-preview h2{font-size:22px;padding-bottom:6px;border-bottom:1px solid var(--md-border)}.markdown-preview h3{font-size:18px}.markdown-preview h4{font-size:15px}.markdown-preview p,.markdown-preview ul,.markdown-preview ol,.markdown-preview blockquote,.markdown-preview pre,.markdown-preview table{margin:0 0 1em}.markdown-preview a{color:#175cd3}.markdown-preview blockquote{margin-left:0;border-left:4px solid #98a2b3;background:#f8fafc;color:#475467;padding:8px 14px}.markdown-preview code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:var(--md-code);border-radius:4px;padding:.15em .35em}.markdown-preview pre{overflow:auto;background:#101828;color:#f2f4f7;border-radius:7px;padding:14px}.markdown-preview pre code{display:block;padding:0;background:transparent}.markdown-preview table{width:100%;border-collapse:collapse;display:block;overflow:auto}.markdown-preview th,.markdown-preview td{border:1px solid var(--md-border);padding:7px 10px}.markdown-preview th{background:#f8fafc}.markdown-preview img{max-width:100%;height:auto}
.markdown-preview .hljs-comment,.markdown-preview .hljs-quote{color:#7ee787;font-style:italic}.markdown-preview .hljs-keyword,.markdown-preview .hljs-selector-tag,.markdown-preview .hljs-subst{color:#ff7b72}.markdown-preview .hljs-string,.markdown-preview .hljs-doctag,.markdown-preview .hljs-regexp{color:#a5d6ff}.markdown-preview .hljs-number,.markdown-preview .hljs-literal,.markdown-preview .hljs-variable{color:#79c0ff}.markdown-preview .hljs-title,.markdown-preview .hljs-section{color:#d2a8ff}.markdown-preview .hljs-type,.markdown-preview .hljs-built_in{color:#ffa657}.markdown-preview .hljs-attr,.markdown-preview .hljs-name{color:#7ee787}.markdown-preview .hljs-meta,.markdown-preview .hljs-symbol,.markdown-preview .hljs-bullet{color:#e3b341}.markdown-preview .hljs-addition{color:#aff5b4}.markdown-preview .hljs-deletion{color:#ffdcd7}
.markdown-diagram{overflow:auto;margin:0 0 1em;padding:16px;border:1px solid var(--md-border);border-radius:7px;background:#fff}.markdown-diagram svg{display:block;max-width:100%;height:auto;margin:0 auto}.markdown-diagram.is-invalid{color:#b42318;background:#fef3f2;border-color:#fecdca;white-space:pre-wrap}
.markdown-source-editor{position:relative;flex:1;min-height:0;background:#fff;overflow:hidden}.markdown-source,.markdown-source-highlight{position:absolute;inset:0;width:100%;height:100%;box-sizing:border-box;margin:0;border:0;padding:16px;white-space:pre;overflow:auto;font:12.5px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;tab-size:2}.markdown-source-highlight{pointer-events:none;color:#344054;background:#fff}.markdown-source{z-index:1;resize:none;outline:0;color:transparent;background:transparent;caret-color:#101828;-webkit-text-fill-color:transparent}.markdown-source::selection{background:#b9d6ff;-webkit-text-fill-color:transparent}.markdown-source-highlight .hljs-section,.markdown-source-highlight .hljs-strong{color:#175cd3;font-weight:700}.markdown-source-highlight .hljs-emphasis{color:#7f56d9;font-style:italic}.markdown-source-highlight .hljs-bullet,.markdown-source-highlight .hljs-number{color:#b54708}.markdown-source-highlight .hljs-link,.markdown-source-highlight .hljs-string{color:#067647}.markdown-source-highlight .hljs-code,.markdown-source-highlight .hljs-quote{color:#475467}.markdown-source-highlight .hljs-meta,.markdown-source-highlight .hljs-symbol{color:#c11574}.markdown-message{padding:10px 13px;border:1px solid #fecdca;border-radius:7px;color:#b42318;background:#fef3f2;white-space:pre-wrap}.is-hidden{display:none!important}
@media(max-width:760px){.markdown-shell{padding:10px}.markdown-header{flex-wrap:wrap}.markdown-workspace,.markdown-workspace.is-split{grid-template-columns:minmax(0,1fr)}.markdown-workspace.is-split{grid-template-rows:repeat(2,minmax(0,1fr))}.markdown-workspace.is-split .markdown-source-panel{grid-column:1;grid-row:1}.markdown-workspace.is-split .markdown-preview-panel{grid-column:1;grid-row:2}.markdown-preview{padding:16px}}
`;

export function ensureMarkdownViewerStyles(): void {
    if (typeof document === 'undefined' || document.getElementById('markdown-viewer-runtime-styles')) return;
    const style = document.createElement('style');
    style.id = 'markdown-viewer-runtime-styles';
    style.textContent = MARKDOWN_VIEWER_CSS;
    document.head.appendChild(style);
}
